### ISSUE TITLE
Atualizar url ao selecionar filtro ou politico

### ISSUE THREAD

**Issue by AbraaoAlves** [analytics-ufcg/empenhados-patrimonio-app#85]
Isso possibilitará o compartilhamento mais facil de uma pesquisa feita.

**Comment by gileadekelvin** [comment]
Olá @AbraaoAlves, agora é possível compartilhar uma URL com o filtro selecionado ou até mesmo candidato específico.
http://capitaldoscandidatos.info/?cargo=deputado-federal&situacao=eleito&ano=2014&estado=qualquer-estado
