### ISSUE TITLE
Instalação de dependências

### ISSUE THREAD

**Issue by jeffersonrpn** [analytics-ufcg/empenhados-patrimonio-app#90]
Não consegui rodar a aplicação, provavelmente há algum conflito de versão do rx/js.
Erro ao rodar **ng serve** ou **ng build**.

```
ERROR in node_modules/@angular/flex-layout/core/typings/observable-media/observable-media.d.ts(1,22): error TS2305: Module '"/usr/local/workspace/empenhados-patrimonio-app/node_modules/rxjs/Rx"' has no exported member 'Subscribable'.
```

**Comment by gileadekelvin** [comment]
Qual a versão do angular-cli (```ng -v```) você tem instalada?

**Comment by jeffersonrpn** [comment]
Deu certo instalando a versão específica do flex-layout. Mas não entendi porque o npm não já fez isso já que está indicado no **package.json**

`npm install @angular/flex-layout@5.0.0-beta.15`
