### ISSUE TITLE
Permalink

### ISSUE THREAD

**Issue by danielfireman** [analytics-ufcg/empenhados-patrimonio-app#99]
Venho usado muito o site como referência para incentivar discussões em rodas de amigos. Uma coisa que seria muito bacana nessas discussões é a possibilidade de poder compartilhar um permalink que levaria a página exatamente como está. Por exemplo:

Estava numa discussão sobre um determinado deputa e para poder mostrar o que eu queria eu tive que:

* abrir a página
* filtrar pelo estado de alagoas
* selecionar o deputado deferal em questão
* Selecionar a escala linar

Gostria muito de poder compartilhar um link que levasse a essa configuração (ao invés da sequencia de passos, que foi o que tive que fazer).

Isso também favoreceria compartilhamentos via redes sociais.

**Comment by gileadekelvin** [comment]
Olá @danielfireman, agora é possível compartilhar um link para um filtro selecionado ou até mesmo um para um candidato específico. 
http://capitaldoscandidatos.info/?cargo=deputado-federal&situacao=que-declararam-patrim%C3%B4nio&ano=2018&estado=al

**Comment by danielfireman** [comment]
Show!
